config/routes.rb
Rails.application.routes.draw do
  resources :rates do
    collection { post :import }
  end  
  resources :items do
    collection { post :import }
  end  
  root 'static_pages#landing'
  get 'static_pages/import'
  get 'static_pages/import2'
  get 'static_pages/import3'
  get 'static_pages/admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  
  scope :by_skuid, -> (skuid) { where(skuid: skuid) if skuid.present? }
  
  #Check if all items in CSV are valid
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Item.create! row.to_hash
    end  
  end
 
end

app/models/rate.rb
class Rate < ApplicationRecord
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Rate.create! row.to_hash
    end  
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    Rails.logger.debug("index.params=#{params}")
    
    #Find rate for szip and dzip supplied
    @cost1 = Rate.where(szip: params[:szip], dzip: params[:dzip]).first.onelbs if params[:szip].present?
    
    #Find item by the skuid supplied
    @items = Item.by_skuid(params[:skuid])
    
    #Calculate Shipping cost 
    @shippingcost = (@cost1 * @items.first.weight) if params[:szip].present?
    
    #Determine profitability of Item based on shipping cost
    @items.each { |x| x.profitable = @shippingcost < x.price ? "Yes" : "No"  if params[:szip].present?}
    
    #Suggest multiple for loss making items
    @items.each { |x| x.multiple = @shippingcost > x.price ? (@shippingcost/x.price).ceil : "Null"  if params[:szip].present?}
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  #Import from CSV feature
  def import
    Item.import(params[:file])
    redirect_to items_path, notice: "Products imported."
  end
  
  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:skuid, :description, :price, :length, :width, :height, :weight, :multiple, :profitable)
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: [:show, :edit, :update, :destroy]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to @rate, notice: 'Rate was successfully created.' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #Import from CSV feature
  def import
    Rate.import(params[:file])
    redirect_to rates_path, notice: "Rate card imported."
  end
  
  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to rates_url, notice: 'Rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:szip, :dzip, :onelbs, :twolbs, :fivelbs, :tenlbs)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
  
  def import
  end
  
  def import2
  end
  
  def import3
  end
  
  def admin
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skuid %>
    <%= f.number_field :skuid %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :length %>
    <%= f.text_field :length %>
  </div>

  <div class="field">
    <%= f.label :width %>
    <%= f.text_field :width %>
  </div>

  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>
  
  <div class="field">
    <%= f.label :multiple %>
    <%= f.text_field :multiple %>
  </div>
  
  <div class="field">
    <%= f.label :profitable %>
    <%= f.text_field :profitable %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<br><br><br>
<p id="notice"><%= notice %></p>

<div class="row">
    <h5 style="margin-top: 70px">Items</h5>
    <hr style="margin-top: 0; margin-bottom: 40px;">
    
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Skuid</th>
          <th>Description</th>
          <th>Price</th>
          <th>Length</th>
          <th>Width</th>
          <th>Height</th>
          <th>Weight(in lbs)</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.skuid %></td>
            <td><%= item.description %></td>
            <td><%= item.price %></td>
            <td><%= item.length %></td>
            <td><%= item.width %></td>
            <td><%= item.height %></td>
            <td><%= item.weight %></td>
            <td><%= link_to 'Show', item %></td>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skuid:</strong>
  <%= @item.skuid %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Length:</strong>
  <%= @item.length %>
</p>

<p>
  <strong>Width:</strong>
  <%= @item.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @item.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @item.weight %>
</p>

<p>
  <strong>Multiple:</strong>
  <%= @item.multiple %>
</p>

<p>
  <strong>Profitable:</strong>
  <%= @item.profitable %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ignite-Geo Spatial OMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" id="main">
      <nav class="navbar navbar-fixed-top navbar-light bg-faded">
        <div class="container">
          <a class="navbar-brand" href="/static_pages/admin">IGnite</a>
        </div><!-- end Container within Navbar --> 
      </nav><!-- end Navbar --> 
    
      <%= yield %>
    </div><!-- end main container -->
  </body>
</html>

app/views/rates/_form.html.erb
<%= form_for(rate) do |f| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :szip %>
    <%= f.number_field :szip %>
  </div>
  
  <div class="field">
    <%= f.label :state1 %>
    <%= f.text_field :state1 %>
  </div>
  
  <div class="field">
    <%= f.label :dzip %>
    <%= f.number_field :dzip %>
  </div>
  
  <div class="field">
    <%= f.label :state2 %>
    <%= f.text_field :state2 %>
  </div>
  
  <div class="field">
    <%= f.label :onelbs %>
    <%= f.text_field :onelbs %>
  </div>

  <div class="field">
    <%= f.label :twolbs %>
    <%= f.text_field :twolbs %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<br><br><br>
<p id="notice"><%= notice %></p>

<div class="row">
  <h5 style="margin-top: 70px">Rates</h5>
  <hr style="margin-top: 0; margin-bottom: 40px;">
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Szip</th>
        <th>State1</th>
        <th>Dzip</th>
        <th>State2</th>
        <th>1lbs(in $)</th>
        <th>2lbs(in $)</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @rates.each do |rate| %>
        <tr>
          <td><%= rate.szip %></td>
          <td><%= rate.state1 %></td>
          <td><%= rate.dzip %></td>
          <td><%= rate.state2 %></td>
          <td><%= rate.onelbs %></td>
          <td><%= rate.twolbs %></td>
          <td><%= link_to 'Show', rate %></td>
          <td><%= link_to 'Edit', edit_rate_path(rate) %></td>
          <td><%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Rate', new_rate_path %>

app/views/rates/new.html.erb
<h1>New Rate</h1>

<%= render 'form', rate: @rate %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Szip:</strong>
  <%= @rate.szip %>
</p>

<p>
  <strong>Dzip:</strong>
  <%= @rate.dzip %>
</p>

<p>
  <strong>Onelbs:</strong>
  <%= @rate.onelbs %>
</p>

<p>
  <strong>Twolbs:</strong>
  <%= @rate.twolbs %>
</p>

<p>
  <strong>Fivelbs:</strong>
  <%= @rate.fivelbs %>
</p>

<p>
  <strong>Tenlbs:</strong>
  <%= @rate.tenlbs %>
</p>

<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>

app/views/static_pages/admin.html.erb
<!-- First Row
=================-->

  <div class="row" style="margin-top: 90px">
    <div class="col-sm-12">
      <h3>Item Management</h3>
      <hr style="margin-top: 0; margin-bottom: 30px;">
    </div>  
  </div>
  
  <div class="row">
    <div class="col-sm-4 col-md-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Manage Active Items</h4>
          <p class="card-text">Manage the lifecycle of active items and modify Item attributes.</p>
          <a href="/items" class="btn btn-primary">View</a>
        </div>
      </div>  
    </div>

    <div class="col-sm-4 col-md-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Import Items</h4>
          <p class="card-text">Incrementally Import Items using a CSV or an Excel file.</p>
          <a href="/static_pages/import" class="btn btn-primary">Import</a>
        </div>
      </div>  
    </div>
  </div>
  
  <div class="row" style="margin-top: 50px">
    <div class="col-sm-12">
      <h3>Rate Management</h3>
      <hr style="margin-top: 0; margin-bottom: 30px;">
    </div>  
  </div>
  
  <div class="row">
    <div class="col-sm-4 col-md-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Manage Rates</h4>
          <p class="card-text">Manage rate card attributes between zones.</p>
          <a href="/rates" class="btn btn-primary">View</a>
        </div>
      </div>  
    </div>

    <div class="col-sm-4 col-md-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">Import Rates</h4>
          <p class="card-text"><br>Import rate card for zip codes.</p>
          <a href="/static_pages/import2" class="btn btn-primary">Import</a>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row" style="margin-top: 50px">
    <div class="col-sm-12">
      <h3>RESTful API</h3>
      <hr style="margin-top: 0; margin-bottom: 30px;">
    </div>  
  </div>

  <div class="row">
    <div class="col-sm-4 col-md-4">
      <div class="card">
        <div class="card-block">
          <h4 class="card-title">API Demo</h4>
          <p class="card-text">Simulate API calls from OMS with query parameters.</p>
          <a href="/static_pages/import3" class="btn btn-primary">View</a>
        </div>
      </div>  
    </div>
  </div>  

app/views/static_pages/import.html.erb
<h5 style="margin-top: 90px">Import Items</h5>
<hr style="margin-top: 0; margin-bottom: 60px;">

  <%= form_tag import_items_path, multipart: true do %>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag("Import", :class=>"btn btn-default", :style=>"margin-top: 30px") %>
  <% end %>
  
<h5 style="margin-top: 60px">Instructions</h5>
<hr style="margin-top: 0; margin-bottom: 30px;">  

<dl class="dl-horizontal">
  <dt>File Format</dt>
  <dd>Only CSV (Comma Separated Values) files can be used to import multiple items at once.</dd>
  <dt>Specifications</dt>
  <dd>The first row of the CSV must be the column headers.</dd>
  <dt>Field Validations</dt>
  <dd>All values must conform to the corresponding field constraints.</dd>
  <dt>Warning</dt>
  <dd>Even if a single Item fails validation check, entire CSV file will be disqualified.</dd>
</dl>  

app/views/static_pages/import2.html.erb
<h5 style="margin-top: 90px">Import Rates</h5>
<hr style="margin-top: 0; margin-bottom: 60px;">

  <%= form_tag import_rates_path, multipart: true do %>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag("Import", :class=>"btn btn-default", :style=>"margin-top: 30px") %>
  <% end %>
  
<h5 style="margin-top: 60px">Instructions</h5>
<hr style="margin-top: 0; margin-bottom: 30px;">  

<dl class="dl-horizontal">
  <dt>File Format</dt>
  <dd>Only CSV (Comma Separated Values) files can be used to import rate card.</dd>
  <dt>Specifications</dt>
  <dd>The first row of the CSV must be the column headers.</dd>
  <dt>Field Validations</dt>
  <dd>All values must conform to the corresponding field constraints.</dd>
  <dt>Warning</dt>
  <dd>Even if a single Item fails validation check, entire CSV file will be disqualified.</dd>
</dl>  

app/views/static_pages/import3.html.erb
<h5 style="margin-top: 90px">API Calls Instructions</h5>
<hr style="margin-top: 0; margin-bottom: 60px;">

<dl class="dl-horizontal">
  <dt>Item Export</dt>
  <dd>https://ignitesaas.herokuapp.com/items.json</dd>
  <dt>Rate Export</dt>
  <dd>https://ignitesaas.herokuapp.com/rates.json</dd>
  <dt>API Query Parameters</dt>
  <dd>Item attributes can queried using skuid parameter.</dd>
  <dd>szip is the zipcode of the fulfilling warehouse.</dd>
  <dd>dzip is the customer's zip code.</dd>
  <dt>Simulate short distance profitable scenario</dt>
  <dd>https://ignitesaas.herokuapp.com/items.json?skuid=123&szip=33101&dzip=30301</dd>
  <dt>Simulate long distance unprofitable scenario</dt>
  <dd>https://ignitesaas.herokuapp.com/items.json?skuid=123&szip=33101&dzip=94101</dd>
</dl> 

app/views/static_pages/landing.html.erb
</div><!-- end main container from application.html.erb -->

  <section class="page-header">
    <h1 class="project-name">IGnite</h1><br>
    <h2 class="project-tagline">Geospatial Order Management Module</h2>
    
    <a href="/static_pages/admin" class="btn">Get Started</a>
    
  </section>

<div class="container"><!-- Restart the main container from application.html.erb -->